### ISSUE TITLE
Crash when trying to import families

### ISSUE THREAD

**Issue by jonathansayag** [akeneo/ExcelInitBundle#13]
Hi,

I'm going to migrate my Akeneo from **1.5** to **1.6** and i've got some troubles with the init.xlsx import. 

When i launch the import process, it already crashed cause of Family import. As you you said in `README.md`, i check the `code` / `name` of channels in **channel tab**, but it still does not works.

What do i have to check too ?

Thanks for support.

Jonathan

**Comment by jonathansayag** [comment]
I just found that it is the custom attributes that break the family import. Is there something different about custom attribute between Akeneo 1.5 & 1.6 ?

**Comment by faducrocq** [comment]
Hi, 

Precisely, we have the following error : 
<img width="945" alt="2017-01-03_17h26_23" src="https://cloud.githubusercontent.com/assets/24897983/21614452/c92ee0fc-d1d9-11e6-99db-18aa91734b94.png">

We can create and import common attributes for the different families but when we create attributes specifics to some families, the error occures. Does someone ever have had this error ?

**Comment by jmleroux** [comment]
Hello,

could you verify that the "coifee" attribute is present in the `attributes` worksheet? All atributes must be previously defined in this sheet.

Regards,
JM

**Comment by faducrocq** [comment]
Hello,

We have added all the attributes in the attributes worksheet so now it works but I don't understand why we cannot anymore defined specifics attributes in the families worksheets.

Regard,

Fanny

**Comment by jmleroux** [comment]
I fixed the documentation to set this feature as deprecated, but we will study the possibility to re-enable it.
