### ISSUE TITLE
asset_categories.csv not being imported on 1.7 EE

### ISSUE THREAD

**Issue by nei** [akeneo/ExcelInitBundle#31]
It seems the init is broken for 1.7 EE.

When it try to load the asset_categories.csv it break with this error.

```[2017-03-27 15:58:51] translation.WARNING: Translation not found. {"id":"Catchable Fatal Error: Argument 2 passed to PimEnterprise\\Bundle\\SecurityBundle\\Manager\\CategoryAccessManager::buildGrantAccess() must implement interface Pim\\Component\\User\\Model\\GroupInterface, null given, called in /akeneo-ee/vendor/akeneo/pim-enterprise-dev/src/PimEnterprise/Bundle/SecurityBundle/Manager/CategoryAccessManager.php on line 160 and defined","domain":"messages","locale":"en"}```

If I comment out the content of this file and the access file it works.

**Comment by jmleroux** [comment]
i think we can close this one.
