### ISSUE TITLE
Errors with init bundle & akeneo 1.6 EE

### ISSUE THREAD

**Issue by chrey** [akeneo/ExcelInitBundle#5]
**First problem**
In Akeneo 1.6EE and the minimal installer, the command php app/console pim:installer:db fails with an error looking for init.xlsx in the enterprise minimal bundle. 

**Second problem**
With a custom installer bundle & Akeneo 1.6EE, the command fails because the user_groups.csv file must be imported before the init file so that the category can be imported with an existing user group.  

`[2016-09-29 15:47:41] batch.ERROR: Encountered an error executing the step: Catchable Fatal Error: Argument 2 passed to PimEnterprise\Bundle\SecurityBundle\Manager\CategoryAccessManager::buildGrantAccess() must be an instance of Oro\Bundle\UserBundle\Entity\Group, null given, called in /home/smile/pim/vendor/akeneo/pim-enterprise-dev/src/PimEnterprise/Bundle/SecurityBundle/Manager/CategoryAccessManager.php on line 154 and defined`

We put a position of 15 to the user_group.csv import to solve the problem and import it before the init file.

Charlotte

**Comment by jmleroux** [comment]
Hello @chrey ,
thank you for reporting this issue. As you know how to fix this problem, it could be a good time to start contributing to this bundle. Feel to open a Pull Request and i will merge it with pleasure.

Regards,
JM

**Comment by chrey** [comment]
Hi @jmleroux , 
Yes, one of my colleagues will do the merge request with other fixes as soon as he finds time to do it (beginning of next week certainly) !
Charlotte

**Comment by jmleroux** [comment]
Thanks for the pull request, i just merged it.
