### ISSUE TITLE
Akeneo 2.1.*

### ISSUE THREAD

**Issue by francescopis** [akeneo/ExcelInitBundle#59]
Please check if is it compatible with akeneo 2.1.* and change composer requirements

**Comment by jmleroux** [comment]
Hello @francescopis ,

Did you already check on your side?

Regards,
JM

**Comment by francescopis** [comment]
tested on 2.1.1 without problems

**Comment by jmleroux** [comment]
Thx a lot. I updated the master composer.json and will tag after a CI modification.

**Comment by jmleroux** [comment]
HINT: If you had the time to make a PR on the README to change the requirements, you would have your name in the contributors list. ;)

**Comment by jmleroux** [comment]
merged
